
=== *fs.read*(_String_) -> _String_
Read specified file.

Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| File path
|===

=== Returns
[width="72%"]
|===
|string| Contents of file
|===

=== *fs.write*(_String_, _String_) -> _Boolean_
Write string(#2) to file(#1).

Returns boolean `true` if successful.
Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| File path
|string| String to write
|===

=== Returns
[width="72%"]
|===
|boolean| `true` if successful
|===

=== *fs.isdir*(_String_) -> _Boolean_
Check if specified path is a directory.

Returns boolean `true` if it is a directory.
Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| Path
|===

=== Returns
[width="72%"]
|===
|boolean| `true` if path is a directory
|===

=== *fs.isfile*(_String_) -> _Boolean_
Check if specified path is a file.

Returns boolean `true` if it is a file, `false` otherwise.
Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| File path
|===

=== Returns
[width="72%"]
|===
|boolean| `true` if path is a file
|===

=== *fs.mkdir*(_String_) -> _Boolean_
Create directory.

Returns boolean `true` if successful.
Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| Directory path
|===

=== Returns
[width="72%"]
|===
|boolean| `true` if successful
|===

=== *fs.rmdir*(_String_) -> _Boolean_
Remove directory.

Returns boolean `true` if successful.
Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| File path
|===

=== Returns
[width="72%"]
|===
|boolean| `true` if successful
|===

=== *fs.chdir*(_String_) -> _Boolean_
Change current working directory. This changes the CWD for the whole script.

Returns boolean `true` if successful.
Returns `nil` and an error message when an error is encountered.

=== Arguments
[width="72%"]
|===
|string| File path
|===

=== Returns
[width="72%"]
|===
|boolean| `true` if successful
|===

=== *fs.currentdir*() -> _String_
Show the current working directory.

Returns the full path of the current directory.
Returns `nil` and an error message when an error is encountered.

=== Returns
[width="72%"]
|===
|string |Current directory path
|===

=== *fs.attributes*(_String_) -> _Table_
Get the attributes of specified path.

Returns a table(map) of the file system attributes.
Returns `nil` and an error message when an error is encountered.

=== Returns
[width="72%"]
|===
|table |Map of attributes
|===

=== Map(Unix)
[width="72%"]
|===
|dev |Device where the inode resides
|ino |Inode number
|mode |Mode(file, dir, link, socket, pipe, device)
|nlink |Number of hard links to the file
|uid |UID of owner
|gid |GID of owner
|rdev |Device type
|access |Time of last access
|modification |Time of last modification
|change |Time of last file status change
|size |File size in bytes
|permissions |File permissions string
|blocks |Block allocated for file
|blksize |Optimal FS blocksize
|===

=== *fs.symlinkattributes*(_String_) -> _Table_
Get the attributes of a symlink, not the path it refers to.

Returns a table(map) of the file system attributes.
Returns `nil` and an error message when an error is encountered.

=== Returns
[width="72%"]
|===
|table |Map of attributes, see `fs.attributes` map
|===

=== *fs.link*(_String_, _String_, [,_Boolean_]) -> _Boolean_
Create a file system link.

First argument is the target path. Second is the new link.
Creates a hard link by default. If the optional third argument is set to `true` then a symlink is created insteed.

Returns `true` if successful.
Returns `nil` and an error message when an error is encountered.

=== Returns
[width="72%"]
|===
|boolean | `true` if successful
|===

=== *fs.dir*(_String_) -> _Function_
Return an iterator that walks the specified path.

Returns an `iterator` if no errors encountered.
Returns `nil` and an error message when an error is encountered.

=== Returns
[width="72%"]
|===
|function| An iterator
|===

=== *fs.touch*(_String_[, _Number_][, _Number_]) -> _Boolean_
Sets access and modification times of an specified path. The first argument is the path to change, the second argument is the access time, and the third argument is the modification time. If the modification time is omitted, the access time provided is used. If both arguments are omitted, the current time is used.

Returns `true` if successful.
Returns `nil` and an error message when an error is encountered.

=== Returns
[width="72%"]
|===
|function| An iterator
|===
