
=== *string.append*(_String_, _String_) -> _String_
Append newline plus argument #2 string to argument #1 string.

=== Arguments
[width="72%"]
|===
|string| Original string
|string| String to append
|===

=== Returns
[width="72%"]
|===
|string| New string
|===

=== Example
----
local s = 'one'
local x = s:append'two'
assert(x=='one\ntwo')
----

=== *string.line_to_list*(_String_) -> _Table_
Create a new table(list) where each line of argument #1 is a value in the list.

=== Arguments
[width="72%"]
|===
|string| Source string
|===

=== Returns
[width="72%"]
|===
|table| New table
|===

=== Example
----
local s = [[five
six
seven]]
local t = s:line_to_list()
-- t will contain { "five", "six", "seven" }
----

=== *string.word_to_list*(_String_) -> _Table_
Create a new table(list) where each alphanumeric sequence of argument #1 is a value in the list.

=== Arguments
[width="72%"]
|===
|string| Source string
|===

=== Returns
[width="72%"]
|===
|table| New table
|===

=== Example
----
local n = '1# 2! 3.'
local nt = n:word_to_list()
-- nt will contain { "1", "2", "3" }
----

=== *string.to_list*(_String_) -> _Table_
Create a new table(list) where each non-space(%S) character of argument #1 is a value in the list.

=== Arguments
[width="72%"]
|===
|string| Source string
|===

=== Returns
[width="72%"]
|===
|table| New table
|===

=== Example
----
local z = 'one\ttwo'
local zt = z:to_list()
-- zt will contain {"one", "two"}
----
